#!/bin/bash
#SBATCH -D /home/tvkent/projects/beagle/Pvale-10
#SBATCH -o /home/tvkent/projects/beagle/Pvale-10/slurm-log/chr8-stout.txt
#SBATCH -e /home/tvkent/projects/beagle/Pvale-10/slurm-log/chr8-stderr.txt
#SBATCH -J chr8-10
set -e
set -u

java -Djava.io.tmpdir=/home/tvkent/temp -Xmx80000m -jar beagle.jar unphased=/home/tvkent/projects/beagle/chr8f.gz missing=N fastibdthreshold=1e-10 fastibd=true out=/home/tvkent/projects/beagle/Pvale-10/chr8out
